# Generated by Django 5.0.3 on 2026-04-20 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('food', 'Food/Beverage'), ('merch', 'Merchandise'), ('restroom', 'Restroom'), ('exit', 'Exit')], max_length=50)),
                ('distance_ft', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('density_level', models.CharField(choices=[('safe', 'Safe'), ('warn', 'Warning'), ('danger', 'Danger')], default='safe', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_wait_time', models.IntegerField(help_text='Est wait time in minutes')),
                ('active_orders', models.IntegerField(default=0)),
                ('service_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.servicepoint')),
            ],
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_points', to='api.zone'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.zone')),
            ],
        ),
    ]
